/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.notepadlite;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JuanLamasRubio
 */
public class NotePadLite extends javax.swing.JFrame {
    private String nombrearchivo;
    /**
     * Creates new form NotePadLite
     */
    public NotePadLite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Cargar archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        cuenta.setForeground(new java.awt.Color(255, 51, 0));
        cuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuenta.setText("hola");
        getContentPane().add(cuenta, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /** try( BufferedReader f = new BufferedReader(new FileReader("pom.xml"))) {
            String s;
            String todoelarchivo = "";
            
            while( (s=f.readLine())!=null) {
                todoelarchivo=todoelarchivo+s+"\n";
                //"\n" Para que no aparezca todo en una sola linea 
            }
            
            texto.setText(todoelarchivo);
            
            cuenta.setText( todoelarchivo.length() +"caracteres");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NotePadLite.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NotePadLite.class.getName()).log(Level.SEVERE, null, ex); 
        } */
        
        Properties config = new Properties();
        try {
            config.load( new FileReader("config.properties"));
            nombrearchivo = config.getProperty("archivo", "pom.xml");
            
            File f = new File(nombrearchivo);
            if ( !f.exists()) {
                config.setProperty("archivo", "pom.xml");
                config.store(new FileWriter("config.properties"),"archivo no existe");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NotePadLite.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NotePadLite.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try( Scanner sc = new Scanner( new File("pom.xml "))) {
            
            //sc.useDelimiter("[\n ]");
            String todoelarchivo = "";
            
            
            while( sc.hasNext() ) {
                todoelarchivo += sc.nextLine()+"\n"; //Recorrer un cadena con la clase scanner
            }
            
            texto.setText(todoelarchivo);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NotePadLite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotePadLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotePadLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotePadLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotePadLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotePadLite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
